- name: Add host expired.badssl.com to Zabbix
  community.zabbix.zabbix_host:
    server_url: "http://localhost/zabbix"   # nebo tvá URL
    login_user: Admin
    login_password: zabbix
    host_name: expired.badssl.com
    visible_name: "expired.badssl.com - SSL Check"
    status: enabled
    interfaces:
      - type: agent
        main: 1
        useip: 0
        dns: expired.badssl.com
        port: "10050"
    groups:
      - name: "Linux servers"   # nebo existující skupina
    link_templates:
      - "Template Module ICMP Ping"    # základní
      - "Website certificate by Zabbix agent 2"  # SSL šablona
    state: present